source 'https://rubygems.org'

gem 'sinatra'
gem "slim"
gem "sass"
gem "dm-core"
gem "dm-migrations"
gem "dm-timestamps"
gem "rake"
gem "pg", :group => :production
gem "dm-postgres-adapter",:group => :production
gem "dm-sqlite-adapter", :group => :development
gem "thin"


